/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategorySlugIndexRouteImport } from './routes/$categorySlug/index'
import { Route as CategorySlugProductSlugIndexRouteImport } from './routes/$categorySlug/$productSlug/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugIndexRoute = CategorySlugIndexRouteImport.update({
  id: '/$categorySlug/',
  path: '/$categorySlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugProductSlugIndexRoute =
  CategorySlugProductSlugIndexRouteImport.update({
    id: '/$categorySlug/$productSlug/',
    path: '/$categorySlug/$productSlug/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$categorySlug/': typeof CategorySlugIndexRoute
  '/$categorySlug/$productSlug/': typeof CategorySlugProductSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$categorySlug': typeof CategorySlugIndexRoute
  '/$categorySlug/$productSlug': typeof CategorySlugProductSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$categorySlug/': typeof CategorySlugIndexRoute
  '/$categorySlug/$productSlug/': typeof CategorySlugProductSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$categorySlug/' | '/$categorySlug/$productSlug/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$categorySlug' | '/$categorySlug/$productSlug'
  id: '__root__' | '/' | '/$categorySlug/' | '/$categorySlug/$productSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategorySlugIndexRoute: typeof CategorySlugIndexRoute
  CategorySlugProductSlugIndexRoute: typeof CategorySlugProductSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$categorySlug/': {
      id: '/$categorySlug/'
      path: '/$categorySlug'
      fullPath: '/$categorySlug/'
      preLoaderRoute: typeof CategorySlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$categorySlug/$productSlug/': {
      id: '/$categorySlug/$productSlug/'
      path: '/$categorySlug/$productSlug'
      fullPath: '/$categorySlug/$productSlug/'
      preLoaderRoute: typeof CategorySlugProductSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategorySlugIndexRoute: CategorySlugIndexRoute,
  CategorySlugProductSlugIndexRoute: CategorySlugProductSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
